# Jekyll configuration for GitHub Pages
title: cScan Documentation
description: Cross-Platform Cleanup Assistant for Windows, macOS, and Linux
baseurl: "/cScan"
url: "https://TMHSDigital.github.io"
theme: jekyll-theme-cayman
show_downloads: true
google_analytics: 

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /README.html
  - title: Cross-Platform Guide
    url: /CROSS_PLATFORM_GUIDE.html
  - title: Features
    url: /IMPROVEMENTS.html

# GitHub metadata
github:
  repository_url: https://github.com/TMHSDigital/cScan
  zip_url: https://github.com/TMHSDigital/cScan/archive/main.zip
  tar_url: https://github.com/TMHSDigital/cScan/archive/main.tar.gz

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README_LOCAL.md 